# see https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring:
  application:
    name: opensbpm-sample-e2e

#  main:
#    web-application-type: none
server:
  port: -1

#debug: true
#logging.level:
  #    root: INFO
  #org.opensbpm.engine.e2e.user.UserClient: DEBUG

