#A description about all values is available on https://docs.spring.io/spring-boot/appendix/application-properties/index.html

server:
  servlet:
    context-path: /api

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cloud-dev.opensbpm.org/auth/realms/opensbpm
