# see https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring:
  application:
    name: opensbpm-stresstest-worker

#  main:
#    web-application-type: none
server:
  port: -1

opensbpm:
  url: https://cloud-dev.opensbpm.org
  #authUrl:
  #username: miriam
  #password: miriam

#debug: true
#logging.level:
  #    root: INFO
  #org.opensbpm.engine.e2e.user.UserClient: DEBUG
