# see https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring:
  application:
    name: opensbpm-stresstest-worker

#  main:
#    web-application-type: none
server:
  port: -1

opensbpm:
  url: https://cloud-dev.opensbpm.org
  #authUrl:
  #username: miriam
  #password: miriam
  #starter: true
  statistics:
    url: https://drive.sedelmaier.at/remote.php/dav/files/opensbpm/e2e-client/
    username: opensbpm
    password: opensbpm2025


  #debug: true
#logging.level:
  #    root: INFO
  #org.opensbpm.engine.e2e.user.UserClient: DEBUG

