server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application.name: engine-server
  main.allow-circular-references: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cloud-dev.opensbpm.org/auth/realms/quickstart

#debug: true

logging.level:
#    root: INFO
  org.hibernate.engine.internal.StatefulPersistenceContext: ERROR # avoid HHH000179 info
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: INFO
#    org.apache.cxf: DEBUG
