# This is a basic workflow that is manually triggered

name: Cleanup packages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: 'opensbpm-package'
          min-versions-to-keep: 2
