name: package purge
on:
  #push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  fail_purging_semantic:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: MobileheadHolding/github-action-purge-packages@master
        with:
          #owner: github
          #repo: semantic
          version-regex: 'sha*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
